### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0) out of memory

### ISSUE THREAD

**Issue by wangjuenew** [zhaoweicai/mscnn#10]
I use Titian X GPU which has 12GB video memory , and Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHZ which has 128GB memory.
However, when I run the mscnn-8s-768-trainval-pretrained model using the run_mscnn_detection.m, it occurs "Check failed: error == cudaSuccess (2 vs. 0) out of memory" when run into the code line "outputs = net.forward({test_image}); pertime = toc;"

@zhaoweicai , could you help me how to solve  this problem? thanks a lot.

**Comment by GBJim** [comment]
Hi @wangjuenew 
Please refer to #7

**Comment by wangjuenew** [comment]
@GBJim yeah, it solved, thank you!
