### ISSUE TITLE
about how to use the new cascade RCNN

### ISSUE THREAD

**Issue by pangsu0613** [zhaoweicai/mscnn#102]
Hello! Thank you for sharing your newest work! Could you please provide some instructions on how to use the new cascade RCNN for KITTI 2d object detection benchmark? Many thanks!!

**Comment by zhaoweicai** [comment]
The usage has no much difference with the original mscnn. We have provided the pretrained model for cascade-mscnn. Just use https://github.com/zhaoweicai/mscnn/blob/master/examples/kitti_car/run_cascademscnn.m for running the inference.

**Comment by pangsu0613** [comment]
Thank you for your quick response! Have you done any experiment on KITTI pedestrian and cyclist benchmark?

**Comment by zhaoweicai** [comment]
The goal of the cascade r-cnn is for high quality object detection, but KITTI pedestrian and cyclist use AP50 for evaluation. So I haven't tested on them yet.

**Comment by pangsu0613** [comment]
Ok, I see, thanks for your explanation, but I don't understand the AP50 part, do you mean IoU=0.5?. The Cascade-RCNN includes a sequence of detectors with increasing IoU. But since KITTI uses IoU=0.5 for evaluation, which is a pretty low metric discussed in the paper, so that's the main reason, am I correct ?

**Comment by zhaoweicai** [comment]
Yes, you are correct. When you look at the paper, you can find Cascade R-CNN doesn't have much improvement when the evaluation metric is loose, e.g. AP50 (IoU=0.5).

**Comment by pangsu0613** [comment]
Ok, I think I get it. Thank you so much for your help.
