### ISSUE TITLE
Which model do you use to produce the result in the WIDER Face Result page?

### ISSUE THREAD

**Issue by fengyuentau** [zhaoweicai/mscnn#103]
There are 3 models under [examples/widerface](https://github.com/zhaoweicai/mscnn/tree/master/examples/widerface), which are [mscnn-12x](https://github.com/zhaoweicai/mscnn/tree/master/examples/widerface/mscnn-12s-2x), [mscnn-12x-trainval](https://github.com/zhaoweicai/mscnn/tree/master/examples/widerface/mscnn-12s-2x-trainval) and [cascade-mscnn-12s-align](https://github.com/zhaoweicai/mscnn/tree/master/examples/widerface/cascade-mscnn-12s-align). Judging from the commit time, it cannot be the last one which is used to produce the result in the [WIDER Face Result page](http://shuoyang1213.me/WIDERFACE/WiderFace_Results.html).

Since your paper does not include any details about experiments on WIDER Face, could you tell us which model you use to produce the result in the WIDER Face Result page? Also, by comparing the two files (`mscnn_delopy.prototxt`) from the two directories, I noticed there are some differences in the `detection subnet` part. Could you also tell us why they are different?

Thanks.

**Comment by zhaoweicai** [comment]
``mscnn-12s`` and ``mscnn-12s-trainval`` are identical, but with different training dataset, train and trainval respectively. And their ``mscnn_delopy.prototxt`` are identical. ``cascade-mscnn-12s-align`` is for our work of [Cascade R-CNN](https://github.com/zhaoweicai/cascade-rcnn).

**Comment by fengyuentau** [comment]
@zhaoweicai Thanks, closing this issue.
