### ISSUE TITLE
How to train on different number of classes?

### ISSUE THREAD

**Issue by liz2020** [zhaoweicai/mscnn#104]
I want to use the cascade mscnn on a new dataset (in kitti formate), which have two classes 'car' and 'person'.  So I modify the cls_name in trainval_1st.prototxt, trainval_2nd.prototxt, and mscnn_deploy.prototxt to 3 (2 class + 1 background), and change all the "num_output : 9 " to "num_output: 7". Is this the correct way to follow?

**Comment by CassieMai** [comment]
@liz2020 Should the background be added to the number of classes?

**Comment by liz2020** [comment]
Yes, the number of classes includes the background.

**Comment by CassieMai** [comment]
Thank you @liz2020
