### ISSUE TITLE
Training with different image sizes without croping image

### ISSUE THREAD

**Issue by baiyancheng20** [zhaoweicai/mscnn#11]
Hi, @zhaoweicai have you training models using images with different image sizes without croping?
I have met with problems like followings

> detection_layer.cpp:84] Check failed: height == bottom[1]->height() (86 vs. 85) 
> or
> 
> image_gt_data_layer.cpp:648] Check failed: spatial_dim == label_spatial_dims[nn]

 I have read your codes. I found your codes  `int label_height = round(template_height/(downsample_rates_[nn])); 
    int label_width = round(template_width/(downsample_rates_[nn]));`
`const int label_copy_width = round(copy_width/float(downsample_rates_[nn]));
        const int label_copy_height = round(copy_height/float(downsample_rates_[nn]));`
using simple ways to estimate the output sizes, which may not be consistent with the output sizes after conv operation.

Could you give me a help about how to train models with any image sizes? Thank you.

**Comment by zhaoweicai** [comment]
For the input images, the size should be the multiple of 64. Then, it won't have the size inconsistency.

**Comment by baiyancheng20** [comment]
@zhaoweicai  Thank you. I will check it.
