### ISSUE TITLE
The usage and meaning of the "mu" variable in testing script 

### ISSUE THREAD

**Issue by GBJim** [zhaoweicai/mscnn#13]
Hi @zhaoweicai 
[Lines 37~38 of testing script](https://github.com/zhaoweicai/mscnn/blob/f97b60faa8ace91ce0d9e2d2748fe6669776c4f5/examples/caltech/run_mscnn_detection.m#L37-#L38) initalize  the `mu` variable, then assign values `[104 117 123]` to it.
And in [line 73](https://github.com/zhaoweicai/mscnn/blob/f97b60faa8ace91ce0d9e2d2748fe6669776c4f5/examples/caltech/run_mscnn_detection.m#L73),  testing image subtracts `mu`.

I am not sure about the meaning of these operations, but I guess `mu` is the **Mean** of images.
On each testing image, we need to subtract `[104 117 123]` in R,G,B channels respectively.

Am I correct about this :) ?

**Comment by zhaoweicai** [comment]
They are mean values for B,G,R channels. They are same as used in VGG net.

**Comment by GBJim** [comment]
@zhaoweicai 
Thank you!
