### ISSUE TITLE
Using floating numbers for bbox in window files

### ISSUE THREAD

**Issue by GBJim** [zhaoweicai/mscnn#14]
Hi @zhaoweicai 

I found that bbox coordinates are represented as integers in window files. 
I am wondering if it is possible to use floating number for better precisions. 

Maybe this question is out of the scope,  but I can't find the standards or information about the window files.
Please give me some hint :)

**Comment by zhaoweicai** [comment]
I followed Caffe window_files. With floating coordinates, the files size could be much larger. And I don't think the floating numbers will have noticeable help. Maybe you can give it a try. It is super easy.

**Comment by GBJim** [comment]
@zhaoweicai : 
Thanks!
