### ISSUE TITLE
what is  the format  of  mscnn_window_file_kitti_vehicle_train.txt?  

### ISSUE THREAD

**Issue by liuzhihui2046** [zhaoweicai/mscnn#15]
#3702

/your/KITTI/path/training/image_2/007457.png
3
375
1242
3
1 0 551 190 580 215
2 0 605 182 638 216
4 1 424 166 506 208
5
240 178 285 214
43 184 83 214
647 171 872 203
873 172 1240 221
507 176 559 208

what is  the 1 0 、2 0、４１

**Comment by GBJim** [comment]
Hi @liuzhihui2046 
The line 49 to line 79 of [mscnn_kitti_car_window_file.m](https://gist.github.com/GBJim/4c4b2f8b94150d246fde97aeff55a3ba#file-mscnn_kitti_car_window_file-m-L43-L79) contains the information you are looking for. This is the Matlab script producing window files.
This script can be downloaded from [get_kitti_data.sh](https://github.com/zhaoweicai/mscnn/blob/master/data/get_kitti_data.sh)

**Comment by ck196** [comment]
@GBJim  : Could you explain more details? I do not have Matlab and don't understand Matlab script.
I want to convert this script to Python.

**Comment by ayumiymk** [comment]
This is writed in image_gt_data_layer.cpp
  // window_file format
  // repeated:
  //    # image_index
  //    img_path (abs path)
  //    channels
  //    height
  //    width
  //    num_gts
  //    label ignore x1 y1 x2 y2
  //    num_roni
  //    x1 y1 x2 y2

**Comment by GBJim** [comment]
@ck196 : Sorry I somehow didn't receive the notification and did not notice your post.
Please refer to @ayumiymk's post!

**Comment by moyans** [comment]
@GBJim @zhaoweicai @ayumiymk what's means about the 'ignore' and 'num_roni' ? I want covert my dataset like this .
