### ISSUE TITLE
about evaluate 

### ISSUE THREAD

**Issue by hk003** [zhaoweicai/mscnn#19]
Hi @zhaoweicai
 I've successfully built MSCNN. I have got kitti_8s_768_35k_test_ped.txt. how can I  evaluate by the txt document? 
how can I got the average precision?   (73.7%)

![6 9rw5015bt6begm u0tks](https://cloud.githubusercontent.com/assets/17959876/19523481/3f6d5e24-964d-11e6-8ba4-9854db4bebc7.png)

**Comment by zhaoweicai** [comment]
Hi @hk003 
Please check `readme.txt` and `writeLabels.m` under KITTI devkit. You just need to convert the results to KITTI format for evaluation.
