### ISSUE TITLE
To include CalTech Pedestrian data in future?  

### ISSUE THREAD

**Issue by GBJim** [zhaoweicai/mscnn#2]
Hi @zhaoweicai 
It's great to see MSCNN is released! 

I wonder if the experimental part is going to include CalTech Pedestrian data or not? since it's also part of the experiments on paper.

**Comment by zhaoweicai** [comment]
Yes, the experiments for Caltech dataset will be set up shortly in the future.

**Comment by GBJim** [comment]
@zhaoweicai  Thank you for response :dancer:

**Comment by GBJim** [comment]
Hi @zhaoweicai  Any updates on CalTech Pedestrian data set? :)

**Comment by zhaoweicai** [comment]
hi @GBJim The experiments for Caltech are setup!

**Comment by GBJim** [comment]
Thank you @zhaoweicai !    I will try to run it  :D
