### ISSUE TITLE
Reason why you didn't train cars and pedestrian together?

### ISSUE THREAD

**Issue by jinuhjoo** [zhaoweicai/mscnn#25]
Hello @zhaoweicai 
I was wondering if there was a reason why you didn't train cars and pedestrian together,
but trained them separately?

Thanks and have a great day~

**Comment by zhaoweicai** [comment]
Hi @jinuhjoo 
I was following some other papers. There is no constraint to train a single model. But there are two issues. 1. The numbers of training samples are seriously imbalanced. Car has many more annotations than pedestrian and cyclist. 2. The evaluation metrics are different for car (IOU>=0.7) and ped/cyc (IOU>=0.5). 
You can give it a try to see how it works.

**Comment by jinuhjoo** [comment]
@zhaoweicai 
OK thanks, already on it ~~
hope it will give reasonable results~~
