### ISSUE TITLE
cuDNN 7.0 has not released yet

### ISSUE THREAD

**Issue by GBJim** [zhaoweicai/mscnn#3]
Hi @zhaoweicai

On readme, it says that **For now, only cuDNN 7.0 is supported**.
But based on my knowledge, the latest version of cuDNN is  [cuDNN 5.1](https://developer.nvidia.com/cudnn). 
I guess you actually mean 
only **CUDA** 7.0 is supported.  Am I right?

As for cuDNN. what is the right version for MSCNN?

Thank you :)

**Comment by zhaoweicai** [comment]
Thanks for reminding me. It should be **For now, only CUDA 7.5 with cuDNN v3 is tested**, since we use an old version of Caffe. Earlier version may work too, but the newer ones may not.

**Comment by GBJim** [comment]
@zhaoweicai 
Thank you!  :dancer:
