### ISSUE TITLE
Detection Speed on MSCNN

### ISSUE THREAD

**Issue by jinuhjoo** [zhaoweicai/mscnn#30]
hello @zhaoweicai 
On your paper you mentioned that detection speed reaches up to 10 fps in KITTI original images(1250x375). I have checked and found give or take 100ms~200ms inference time per frame depending on the model (384/576/768 + 2x + c).
If there were room for improvement what part do you think takes the most time in inferencing?

**Comment by zhaoweicai** [comment]
Hi @jinuhjoo 
I can achieve ~10fps on original KITTI images (1250x375) on my lab servers. I believe you can get the same speeds as long as you use Titan GPU and cudnn 3.0. Since the model only has a single forward computation of the input image, the speeds highly depend on the input image size. You can check how much computation each part of the architecture takes, and see where the speed improvement is available. But I think there is no significant room for speed improvement in this detection framework. A couple of straightforward possibilities are reducing the model complexity and input size.

**Comment by songjmcn** [comment]
In my test，I find proposal Layer cost more time（60% times）than other layers，Because the BoxOutputLayer only support cpu model。I think if the BoxOutpututLayer support GPU model，the network will be faster。

**Comment by zhaoweicai** [comment]
Hi @songjmcn 
I can't totally agree that BoxOutputLayer takes about 60% of running time. It is easy to have unfair speed tests. What's your testing case? I test the testing speeds for two major components of model kitti_car mscnn-7s-576. The time for proposal-subnet (the layers before boxoutput layer) is about 0.16s/image, and the time for the rest is about 0.025s/image. Although the absolute speeds may depend on the hardware, the ratio should be close. In my testing, the computation of boxoutput and the above layers takes only 10~15% of the whole computation. 

In BoxOutputLayer, the most expensive part is non-maximum suppression. If the the number of the survived bounding boxes before NMS is around several hundred, the CPU computation of BoxOutputLyaer is not a big problem, which is indeed the case of KITTI detection. If the number is about several thousand, the GPU implementation of NMS will be recommended. 

BTW, the speed will be doubled if the code can run with latest Caffe and CuDNN.

**Comment by jinuhjoo** [comment]
Hello @zhaoweicai 
Before your comment, I found out that the detection speed can be increased up to 14~20FPS on GTX1080 during inference depending on the input size, by reducing the max_nms_num to around 50 ~ 300. This still has limits and does not give any more improvements after a certain threshold.
And I think the input size and the number of "Detection Fields" has quite the influence on its speed.
Oh and do you think reducing "iou_thr" might help with the speed?

I haven't looked at BoxOutputLayer yet, but if you think this is not the case, I might as well not bother with it either.

But is there any chance importing MSCNN to the latest Caffe and cuDNN in the near future? 
If I were to do it myself what layers should I import to the latest Caffe?

Thanks and have a Happy Lunar New Year :-)

**Comment by zhaoweicai** [comment]
hi @jinuhjoo 
The speed is mainly limited by the input size and model complexity. How to speed up the detection framework is always an interesting research topic. 

I am going to have some updates of the code, which is compatible with the latest Caffe and CuDNN. Just wait for a few more days.

**Comment by jinuhjoo** [comment]
Dear @zhaoweicai 
Thanks for the update :-)
I'm setting my environment with the lasted code you updated.
Quick question, could you explain about "fg_thr" in the "proposals" layer(type:BoxOutput)
and why it is set to -7 or -8? Shouldn't it be like 0.5? 
Thanks
--> As I printed out the log, the fg_thr didn't seem to matter as long as it was a minus value,
    since the fg_score was always '0' due to bottom_data[base_idx+k*spatial_dim].
    I will open up another thread if I have other questions, Thanks :-)
