### ISSUE TITLE
What is the value of lambda in the training of KITTI dataset?

### ISSUE THREAD

**Issue by yw155** [zhaoweicai/mscnn#31]
Hi, @zhaoweicai ,
I would like to ask a question that what value of the ratio of negative to positive samples is used in the training of KITTI dataset. Now I set it to 6 in the training, but the trained model is very bad and there are many false positives and large location errors. Do you have any suggestions about the training?

**Comment by zhaoweicai** [comment]
The +/- sample ratio is controlled by ``bg_multiple`` in proposal subnet and ``fg_fraction`` in detection subnet. Please check the .prototxt files and the code.

**Comment by yw155** [comment]
I see it. Thank you!

**Comment by yw155** [comment]
I see it. Thank you!
