### ISSUE TITLE
Issues on the selection of training data

### ISSUE THREAD

**Issue by du0002in** [zhaoweicai/mscnn#38]
Hi, Zhaowei

I noticed that when carrying out the training, you did not use the ground truth bounding boxes with occlusion greater and equal to 2. May I know the reason why ground truth bounding boxes with occlusion equal to 2 are excluded from the training. When occlusion equals to 2, the boxes are under the difficult category. If they are excluded from the training set, how to make sure that they can be revealed in the testing process? Did you see any drawbacks when taking those boxes into the training process?

Thanks.

**Comment by lixincn2015** [comment]
I have the same question.

**Comment by zhaoweicai** [comment]
Hi @du0002in @lixincn2015 
Sorry for late reply. It is kind of standard to exclude highly occluded objects from training set. The objects with occlusion>=2 are highly occluded, maybe only 10% are visible. Those instances are more background than foreground. Occlusion=1 (0%~50% occlusion) is somehow reasonable. I did try to use all instances, but the performance for Moderate is impaired and for Hard is increased. Anyway, you can choose your own dataset depending your needs.

**Comment by du0002in** [comment]
Thanks for the clarification.
