### ISSUE TITLE
what does "field_xyr" and "field_whr" mean?

### ISSUE THREAD

**Issue by lixincn2015** [zhaoweicai/mscnn#39]
Does the 'r' denotes "range" or "rate"?
And why did you give whr and xyr a limit?
I can't find any comment on this. 
Thank you very much for your help!

const Dtype min_whr = log(Dtype(1)/field_whr);     //default: -1
  const Dtype max_whr = log(Dtype(field_whr));	//default: 1
  const Dtype min_xyr = Dtype(-1)/field_xyr;     	//default: -0.5
  const Dtype max_xyr = Dtype(1)/field_xyr;		//default: 0.5

**Comment by lixincn2015** [comment]
Oh, I understand now, after supply some bounding box regression knowledge.

**Comment by GBJim** [comment]
Hi @lixincn2015 
Can you share the bounding box regression knowledge in here?
 I also want to learn from this :)
