### ISSUE TITLE
Any plans to add Python testing module future?

### ISSUE THREAD

**Issue by GBJim** [zhaoweicai/mscnn#4]
Hi @zhaoweicai 
I've successfully built MSCNN. 

Currently, only Matlab version of detecting module is available, do you have any plan to write a Python version of detecting module in future?  If not, I am going to write one :)

**Comment by zhaoweicai** [comment]
Hi @GBJim 
It is great to hear that you have no problem to run the code. I may not have time to implement the Python version. It is easy to re-implement the Python version. It will be appreciated if you could share your re-implementation here. Thanks!

**Comment by GBJim** [comment]
@zhaoweicai 
No problem!

**Comment by jinuhjoo** [comment]
Dear @GBJim
Was there any luck on the python detection model?
If so could you kindly share your code?
Thanks in advance :-)

**Comment by GBJim** [comment]
@jinuhjoo  Yes, I have a fork of MSCNN with the python detection script.
[Click me](https://github.com/GBJim/mscnn/blob/master/examples/caltech/run_mscnn_detection.py)
It only supports CalTech Pedestrian data set. 

The core function is the [im_detect](https://github.com/GBJim/mscnn/blob/master/examples/caltech/run_mscnn_detection.py#L176-#L210) function.
The rest of the codes are mostly for producing the output I need. 

To be noted,I use the [NMS module](https://github.com/rbgirshick/py-faster-rcnn/tree/master/lib/nms) from py-Faster-RCNN to implement python NMS

The script was written pretty badly. Don't depend on it too much :P

**Comment by jinuhjoo** [comment]
@GBJim  This is wonderful! Think it will help a lot :-) 
Thanks again ~

**Comment by chinnikrishna55** [comment]
Can this be used for KITTI?

**Comment by GBJim** [comment]
@chinnikrishna55 
Yes, you can modify my code to do that.

**Comment by ck196** [comment]
I modified @GBJim script for run single image example with kitti_ped_cyc pretrained models
[ped-cyc-mscnn-detection.py](https://gist.github.com/ck196/e22fc3c633678185522f292b6ac506c3)

**Comment by PetreanuAndi** [comment]
@ck196 your repo has a few minor bugs in it, but when i finally cleared those up, running the .py script reveals : 
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 447:20: **Message type "caffe.LayerParameter" has no field named "box_output_param".**
F0403 11:23:21.374938 19888 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: kitti_ped_cyc/mscnn-8s-768-trainval-pretrained/mscnn_deploy.prototxt

It seems like the deploy.prototxt "BoxOutput" type is causing problems.
Any ideas?

**Comment by ahangchen** [comment]
@ck196 your code depends on lib nms, which is no included in mscnn...

**Comment by ahangchen** [comment]
@GBJim how to install nms for mscnn? Any hints about modifying the nms setup.py？

UPDATE:
build nms and copy nms to python site-package direcotry

**Comment by liuwei16** [comment]
Dear @GBJim， have you trained the detector on Caltech by youself ? I have had several trials to re-implement the model training following the instruction provided by the authors, but the detection result on test dataset is far from satisfactory, have you encounterd this problem before?

**Comment by GBJim** [comment]
@liuwei16 
Yes
I actually achieved better result with some tricks
1. Use the [Sanitized CalTech Pedestrian Dataset](https://www.mpi-inf.mpg.de/departments/computer-vision-and-multimodal-computing/research/people-detection-pose-estimation-and-tracking/how-far-are-we-from-solving-pedestrian-detection/) on training and testing data (The original dataset have some false annotations)
2. All the frames are used in the training phase. Additionally, I applied a data filter to filter out the unwanted training data. The filter is designed just like the "Reasonable Setting" in the [CalTech Pedestrian paper.](http://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/files/PAMI12pedestrians.pdf)

I got around  7% miss rate.

But you should achieve acceptable results without any tricks, I guess the miss rate should at least be lower than 13%

**Comment by zhaoweicai** [comment]
@liuwei16 
What is performance you got? I just re-run the exact experiments 4 times today, and the miss rate is 10.33$\pm$0.19. It looks stable to me. If you get the miss rate >12, most likely your experiments have some problems.

**Comment by liuwei16** [comment]
Dear @GBJim is it better when all frames in training dataset is used in your experiment? In my experiments, when every 3 frames are used, the result is inferior to that when every 4 frames are used.
Thank you very much

**Comment by GBJim** [comment]
@liuwei16 

I only tried the every-1 frame setting in my experiment.
Glad you have good experimental result  :)

**Comment by cjjsaic** [comment]
@PetreanuAndi @zhaoweicai Have you guys figure out the problem in "BoxOutput"?

**Comment by cjjsaic** [comment]
@PetreanuAndi  
solve your problem. 

https://github.com/zhaoweicai/mscnn/issues/52

**Comment by cjjsaic** [comment]
@ck196  @zhaoweicai @GBJim 
I can not make mat wrapper successfully on my server. 
I tried your python wrapper on KITTI images. It took 2.3s per frame, which seemed wrong in efficiency. What speed should I achieve approximate for each KITTI test frame?

**Comment by GBJim** [comment]
@cjjsaic 
That processing time looks like running on CPU.
Can you check the GPU usage during testing?  
It could also be lacking cuDNN. You can try it again with cuDNN installed
