### ISSUE TITLE
Failed to parse trainval.prototxt : no field named "detection_param"

### ISSUE THREAD

**Issue by baristahell** [zhaoweicai/mscnn#47]
I wanted to update my MSCNN version in a Docker image i made month ago, so I rebuilt a new image, cloned the current MSCNN version and built it.
The thing is, a test that had no issues in the former image now fails because trainval.prototxt can't be parsed, the `detection_param` parameter isn't recognized.
Don't mind the unconventional filenames etc, i use more or less the `kitty_car/mscnn-7s-576-2x` prototxts.

> Creating training net from net file: data/caffetestprotos/mscnn-kitti/trainval_1st_new.prototxt
> [libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 382:19: Message type "caffe.LayerParameter" has no field named "detection_param".
> F0130 12:30:54.677568    28 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: data/caffetestprotos/mscnn-kitti/trainval_1st_new.prototxt
> *** Check failure stack trace: ***
>     @     0x7f056d3abdaa  (unknown)
>     @     0x7f056d3abce4  (unknown)
>     @     0x7f056d3ab6e6  (unknown)
>     @     0x7f056d3ae687  (unknown)
>     @     0x7f056d9f75ae  caffe::ReadNetParamsFromTextFileOrDie()
>     @     0x7f056db7b0db  caffe::Solver<>::InitTrainNet()
>     @     0x7f056db7c1ac  caffe::Solver<>::Init()
>     @     0x7f056db7c4da  caffe::Solver<>::Solver()
>     @     0x7f056db529f3  caffe::Creator_SGDSolver<>()
>     @           0x40f0fe  caffe::SolverRegistry<>::CreateSolver()
>     @           0x408134  train()
>     @           0x405b3c  main
>     @     0x7f056c3b7f45  (unknown)
>     @           0x4063ab  (unknown)
>     @              (nil)  (unknown)

I use the nvidia/cuda:7.5-cudnn4-devel-ubuntu14.04 image as a base (so cuda 7.5 and cudnn 4).

Does someone know what changed and if it might be because of a dependancy i need to update?
Thanks.

**Comment by PingDong2017** [comment]
I have the same problem when using CUDNN v3. After update CUDNN to v5, the problem is solved. I use cuda 8.0 with cudnn v5.

**Comment by zhaoweicai** [comment]
The name of ``detection_layer`` is changed to ``detection_loss_layer``. Please check the new .prototxt files.

**Comment by baristahell** [comment]
Thanks, didn't see the changes.
