### ISSUE TITLE
"make test" when installing caffe encounter errors at test_detection_layer.cpp

### ISSUE THREAD

**Issue by du0002in** [zhaoweicai/mscnn#5]
Hi, @zhaoweicai 

When I tried to install the Caffe version provided in the repository, I can "make all". But when I tried to "make test", the "test_detection_layer.cpp" encountered errors as following:

CXX src/caffe/test/test_detection_layer.cpp
src/caffe/test/test_detection_layer.cpp: In member function ‘virtual void caffe::DetectionLayerTest_TestGradient_Test<gtest_TypeParam_>::TestBody()’:
src/caffe/test/test_detection_layer.cpp:85:20: error: ‘class caffe::DetectionParameter’ has no member named ‘set_field_r’
   detection_param->set_field_r(2);

I checked with the original Caffe version, I noticed that this "test_detection_layer.cpp" is new. I traced back the "DetectionParameter" in "caffe.pb.cc" and there is NO "set_field_r".

Similar errors occurred when running "test_iou_loss_layer.cpp". It says that the "IOULossParameter" is undefined.

Do you have any suggestions on how to solve these problems?

Thanks.

**Comment by zhaoweicai** [comment]
Hi @du0002in 
I haven't updated the test files for a while. I think you can just ignore `make test`.

**Comment by du0002in** [comment]
Hi,   @zhaoweicai , Got it. Thanks.
