### ISSUE TITLE
Memory saturation during simple classifier tests

### ISSUE THREAD

**Issue by baristahell** [zhaoweicai/mscnn#51]
Hello.
I'm using the pycaffe API to try and run MSCNN on a single image using the following net and pretrained model
`mscnn-8s-768-trainval-pretrained/mscnn_deploy.prototxt`
`mscnn-8s-768-trainval-pretrained/mscnn_kitti_trainval_2nd_iter_35000.caffemodel`

No matter what i do (use `caffe.Net`+`net.forward` or `net.Classifier`+`net.predict`) i end up with my memory (8Go) and swap (30Go) being saturated and the script crashing.
Manually killing the process shows it's stuck in `self._forward`.

In GPU mode i get the infamous `Check failed: error == cudaSuccess (2 vs. 0) out of memory` line before anything starts.

Did anyone get these memory issues? 

EDIT : ok, seems like i clearly lack memory.

**Comment by zhaoweicai** [comment]
Do you use cuDNN? If you use, I don't thing there is an issue of out-of-memory, especially for testing. For the pretrained model with input 768x2560, it usually takes ~5G memory.

**Comment by davvdg** [comment]
Hi ! Unfortunately we don't have a gpu with enough memory to do the job so
we rely on cpu only...
