### ISSUE TITLE
loading pretrained model

### ISSUE THREAD

**Issue by k0suke-murakami** [zhaoweicai/mscnn#52]
I got an error `Message type "caffe.LayerParameter" has no field named "box_output_param".` while loading pretrained model in python. 

Python code is here, 
`net = caffe.Net("examples/kitti_car/mscnn-8s-768-trainval-pretrained/mscnn_deploy.prototxt", 
                    "examples/kitti_car/mscnn-8s-768-trainval-pretrained/mscnn_kitti_trainval_2nd_iter_35000.caffemodel",
                    caffe.TEST)`

Could anybody help me out?

**Comment by MSutt** [comment]
You are not importing the right version of caffe by doing `import caffe` you have to import the caffe which is in mscnn/python/caffe
To do so, you can before insert this :
```python
import sys
sys.path.insert(0, "path/to/mscnn/python")
``` 
then 
```python
import caffe
```

**Comment by k0suke-murakami** [comment]
Thanks! Your code works!
