### ISSUE TITLE
How to generate Fig. 6 2nd row in the paper

### ISSUE THREAD

**Issue by du0002in** [zhaoweicai/mscnn#55]
Hi, @zhaoweicai 

May I check how to generate the smooth curves shown in the Fig. 6  2nd row plots? How many IoU overlap thresholds did you use? Are there any general guidelines? How is the number in the legend calculated, e.g. MS-CNN 62.2? Thanks.

**Comment by zhaoweicai** [comment]
Hi @du0002in 
I used the [code](http://www.cs.toronto.edu/objprop3d/). It is from the standard [proposal evaluation tool](https://www.mpi-inf.mpg.de/departments/computer-vision-and-multimodal-computing/research/object-recognition-and-scene-understanding/how-good-are-detection-proposals-really/)

**Comment by du0002in** [comment]
Got it. Thanks.
