### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by tanger830** [zhaoweicai/mscnn#58]
I got " failed: error == cudaSuccess (2 vs. 0)  out of memory" when run the run_mscnn_detection.m file, my GPU is titan x maxwell, is the input file too large?

**Comment by zhaoweicai** [comment]
I believe titan x maxwell is enough to run the demo. Running demo on 2560x768 images only takes 4~5G memory. But you have to use cuDNN.

**Comment by tanger830** [comment]
Yes, it works after add cuDNN, thank you!
