### ISSUE TITLE
GPU memory problem

### ISSUE THREAD

**Issue by lliuz** [zhaoweicai/mscnn#6]
@zhaoweicai 
I've download the pretrained model of '8x_768' for test. But it loged a OOM message. I'm using 1 K40 for test, the memory is equal to Titan used in the papar. 
I try to train the model by myself then, but the  OOM proplem occurs again when I using the default batch size, and when I reduce the batch size by half, It seems normal but uses about 10G memory.
It's so strange..

**Comment by lliuz** [comment]
I've solved this problem...

**Comment by coolhebei** [comment]
I also accounted with this problem. Could you tell me how to solve it? Thank you much very!
