### ISSUE TITLE
Cannot download MSCNN-V1.0 from your website

### ISSUE THREAD

**Issue by hkzhang95** [zhaoweicai/mscnn#61]
I'd like to use the older version of your code, but get the following error:
```
The requested URL /projects/mscnn/mscnn_v1.0.zip was not found on this server.
```
Could you please tell me where to download the code?

Thank you very much.

**Comment by zhaoweicai** [comment]
Hi @GodBlessZhk 
You can download it now.

**Comment by hkzhang95** [comment]
@zhaoweicai 
Thank you very much.
