### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by ailh0928** [zhaoweicai/mscnn#68]
when I trained the MSCNN(mscnn-7s-576-2x), I got a error: out of memory, so I changed the batch size, and I trained the MSCNN model successfully. however, when I test the model I trained (run_mscnn_detection.m), I got the same error: out of memory.  Is this related to GPU memory size? I am using ubuntu 14.04 with GPU titan x (12GB memory). All things I did as explained in readme.md.
the error is as follow:
I0417 23:41:11.172020  9173 net.cpp:816] Ignoring source layer loss_cls
I0417 23:41:11.172026  9173 net.cpp:816] Ignoring source layer cls_accuracy
I0417 23:41:11.172032  9173 net.cpp:816] Ignoring source layer loss_bbox
I0417 23:41:11.172039  9173 net.cpp:816] Ignoring source layer bbox_iou
F0417 23:42:35.005249  9173 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Killed

**Comment by zhaoweicai** [comment]
Please have a look at https://github.com/zhaoweicai/mscnn/issues/7 first. Titan X is sufficient to train and test any provided models without changes. When use ``run_mscnn_detection.m``, did you change the image size to 576x1920?

**Comment by ailh0928** [comment]
@zhaoweicai thanks a lot.  i have installed cudnn, but not use it for making caffe. thank you very much!

**Comment by ailh0928** [comment]
@zhaoweicai thanks a lot.  i have installed cudnn, but not use it for making caffe. thank you very much!
