### ISSUE TITLE
GPU memory out

### ISSUE THREAD

**Issue by coolhebei** [zhaoweicai/mscnn#7]
dear zhaowei,

when i run the test detection, the gpu memory is out. my gpu card has 12g memory, where i thought it's enough? i have tested the 7s and 8s modules both. could you help me figure out my problem? thank you very much

**Comment by GBJim** [comment]
@coolhebei 
I haven't implemented the testing module yet, but I guess you can install cuDNN v3 and try it again.

**Comment by coolhebei** [comment]
@GBJim 
it's crazy! thanks a lot! i have installed cudnn, but not use it for making caffe. since i neglected the strengthen of it.
thank you very much!

**Comment by antonmil** [comment]
I was having the same issue, and indeed, installing cuda 7.0 and cuDNN v3 resolved it. To compile, I needed to add the cuda 7.0 includes and lib to the Makefile.config and the cuDNN includes and libs into Makefile.

**Comment by zhaoweicai** [comment]
Actually cuda 7.5 works too, which I am working on. I think cudnn v4 will work as well, but not v5. You can also add cuDNN includes and libs into Makefile.config, 
e.g. `INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/local/cudnn-7.0-linux-x64-v3.0/include` and `LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/local/cudnn-7.0-linux-x64-v3.0/lib64`.

**Comment by zhaoweicai** [comment]
The code is merged to the latest caffe. CUDA 8 and cudnn v5 are available to use now.

**Comment by zivtsarfati** [comment]
Will CUDA 9.1 with or without CuDNN 7 be ever supported?
