### ISSUE TITLE
Missing matlab function in the windows generating file

### ISSUE THREAD

**Issue by du0002in** [zhaoweicai/mscnn#8]
hi, @zhaoweicai ,

I think one function is missed in the matlab function 'mscnn_kitti_car_window_file.m'. There is no 'readLabels(label_dir, imgidx)' function being defined.

**Comment by zhaoweicai** [comment]
You should download KITTI devkit, can put it to you KITTI path. In the matlab code, add the path `addpath([root_dir 'devkit_object/devkit/matlab'])`, then it should be working.
